# Site settings
title: DIAG
email: jyskwon@kaist.ac.kr
url: https://diag.kr
description: "DGIST Intelligence Augmentation Group (DIAG) is a team building hybrid intelligence systems &mdash; combining human and machine intelligence to address challenging problems in AI. We do research in the intersection of HCI and AI."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: DIAG.kr

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: github
    url:

# Build settings
markdown: kramdown
permalink: pretty
