# Site settings
title: DIAG
email: jyskwon.github.io
url: https://diag.kr
description: "In the DGIST Intelligence Augmentation Group (DIAG), <br>we build hybrid intelligence systems &mdash; combining human and machine intelligence to address challenging problems in AI. <br>We do research in the intersection of HCI and AI."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: diag.kr

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: jeancrowdvision
#  - title: facebook
#    url:
  - title: github
    url:

# Build settings
markdown: kramdown
permalink: pretty
